-- Migration 007: dashboard infrastructure tables.
--
--   * data_quality_alerts        — discrepancies / anomalies surfaced by ingest.
--                                  NEVER silently reconciled per supervisor's
--                                  third non-negotiable principle.
--   * narrative_cache            — rule-based section narratives, keyed by
--                                  (section, period). Regenerated when ingest
--                                  refreshes underlying data, or when the
--                                  rule-engine version bumps.
--   * social_media_manual_entries — Phase 1 manual-entry forms for social
--                                   metrics. Editor or admin can write;
--                                   everyone authenticated reads. Phase 2 will
--                                   replace with API ingestion.
--
-- Includes RLS policies inline (so this migration is self-contained — alerts
-- and manual entries have role-gated writes that don't fit the uniform pattern
-- in migration 006).


-- ============================================================================
-- data_quality_alerts
-- Examples of alert_type:
--   "bank_vs_weekly_sales_amount_mismatch"
--   "bank_vs_customer_files_amount_mismatch"
--   "unknown_location_threshold_exceeded"
--   "fallback_category_threshold_exceeded"
--   "low_match_confidence_realtor"
--
-- Severity tiers loosely follow log-level conventions; the panel uses them to
-- color-code the alert. resolved + resolved_by + resolution_notes let editors
-- close out alerts after action (per "Editor: ... resolving alerts" in
-- DESIGN_DECISIONS.md).
-- ============================================================================
create table public.data_quality_alerts (
  id                uuid primary key default gen_random_uuid(),
  alert_type        text not null,
  severity          text not null check (severity in ('info', 'warning', 'error')),
  period_year       int,
  period_month      int check (period_month is null or period_month between 1 and 12),
  subject           text not null,
  details           jsonb not null default '{}'::jsonb,
  resolved          boolean not null default false,
  resolved_at       timestamptz,
  resolved_by       uuid references public.profiles(id) on delete set null,
  resolution_notes  text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create trigger set_updated_at before update on public.data_quality_alerts
  for each row execute function public.set_updated_at();

create index data_quality_alerts_resolved_idx
  on public.data_quality_alerts (resolved, severity, created_at desc);
create index data_quality_alerts_period_idx
  on public.data_quality_alerts (period_year, period_month);
create index data_quality_alerts_type_idx
  on public.data_quality_alerts (alert_type);

alter table public.data_quality_alerts enable row level security;

-- Read: any authenticated user.
create policy "authenticated read"
  on public.data_quality_alerts for select to authenticated using (true);

-- Update: editors and admins can resolve alerts. Insert/delete remain
-- service-role only (alerts are emitted by ingest, not created by hand).
create policy "editors and admins update"
  on public.data_quality_alerts for update to authenticated
  using (public.is_editor_or_admin())
  with check (public.is_editor_or_admin());


-- ============================================================================
-- narrative_cache
-- One row per (section_key, period_year, period_month). generator_version is
-- bumped whenever the rule-based narrative engine changes — older rows then
-- get regenerated lazily on next request or on next ingest refresh.
-- ============================================================================
create table public.narrative_cache (
  id                 uuid primary key default gen_random_uuid(),
  section_key        text not null,
  period_year        int not null,
  period_month       int not null check (period_month between 1 and 12),
  narrative_text     text not null,
  generator_version  text not null,
  generated_at       timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint narrative_cache_section_period_uniq
    unique (section_key, period_year, period_month)
);

create trigger set_updated_at before update on public.narrative_cache
  for each row execute function public.set_updated_at();

alter table public.narrative_cache enable row level security;

-- Read: any authenticated user. Writes: service role only (regenerated by
-- the ingest function or a regenerate-narratives Edge Function).
create policy "authenticated read"
  on public.narrative_cache for select to authenticated using (true);


-- ============================================================================
-- social_media_manual_entries
-- Phase 1: form entry per (brand, platform, period, metric). Phase 2 will
-- replace with API-driven ingestion.
-- platform is text rather than a separate ref table because the set is small,
-- stable, and well-known per the brief: PG (FB/IG/YT), PPL (FB/IG),
-- RealVest (FB/IG), Genius (IG only). A CHECK constraint pins the values.
-- metric_key examples: 'followers', 'impressions', 'engagement', 'reach',
-- 'video_views'. Kept open for the form to add new metrics without a migration.
-- ============================================================================
create table public.social_media_manual_entries (
  id            uuid primary key default gen_random_uuid(),
  brand_id      uuid not null references public.brands(id) on delete restrict,
  platform      text not null check (platform in ('facebook', 'instagram', 'youtube', 'tiktok', 'twitter', 'linkedin')),
  period_year   int not null,
  period_month  int not null check (period_month between 1 and 12),
  metric_key    text not null,
  metric_value  numeric not null,
  notes         text,
  entered_by    uuid references public.profiles(id) on delete set null,
  entered_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint social_media_entries_uniq
    unique (brand_id, platform, period_year, period_month, metric_key)
);

create trigger set_updated_at before update on public.social_media_manual_entries
  for each row execute function public.set_updated_at();

create index social_media_entries_brand_idx
  on public.social_media_manual_entries (brand_id);
create index social_media_entries_period_idx
  on public.social_media_manual_entries (period_year, period_month);

alter table public.social_media_manual_entries enable row level security;

-- Read: any authenticated user.
create policy "authenticated read"
  on public.social_media_manual_entries for select to authenticated using (true);

-- Insert + update: editors and admins (manual-entry surface).
create policy "editors and admins insert"
  on public.social_media_manual_entries for insert to authenticated
  with check (public.is_editor_or_admin());

create policy "editors and admins update"
  on public.social_media_manual_entries for update to authenticated
  using (public.is_editor_or_admin())
  with check (public.is_editor_or_admin());

-- Delete: admins only (correcting wrong entries, never editor's call).
create policy "admins delete"
  on public.social_media_manual_entries for delete to authenticated
  using (public.is_admin());
